### ISSUE TITLE
Why would you end training episode if any lives are lost?

### ISSUE THREAD

**Issue by ethancaballero** [dgriff777/rl_a3c_pytorch#1]
Why is this in train.py ?
```
            if args.count_lives:
                if lives > info['ale.lives']:
                    done = True
```

**Comment by ppwwyyxx** [comment]
https://github.com/muupan/async-rl/issues/9

**Comment by dgriff777** [comment]
Just get rid of extra data to speed things up as nothing valuable is learned from agent during transition  from life to life. Helps for a few games, mostly for games that time is a factor

**Comment by ethancaballero** [comment]
Did it help for Breakout?

**Comment by dgriff777** [comment]
no it shouldn't as agent needs to learn to fire once new life starts

**Comment by dgriff777** [comment]
SpaceInvaders it helps a lot. BeamRider I think it helped too. But any game where agent has to learn to start game up again after lost of life its gonna be detrimental

**Comment by dgriff777** [comment]
This is done in Deepminds Alewrap as well as you can see in code here https://github.com/deepmind/alewrap/blob/master/alewrap/GameEnvironment.lua

**Comment by nina124** [comment]
Does args.count_lives help Seaquest-v0? How do you get the pre-trained Seaquest-v0 model?
run `python main.py --env Seaquest-v0 --workers 32 ` for 3 days?
