### ISSUE TITLE
Visualization not appearing

### ISSUE THREAD

**Issue by riccitensor** [dgriff777/rl_a3c_pytorch#16]
I ran `python main.py --env Pong-v0 --workers 32` and 
`python gym_eval.py --env Pong-v0 --num-episodes 100`, but I dont see any visualization of the game. Can i turn it on somehow?

**Comment by dgriff777** [comment]
```Python gym_eval.py --env Pong-v0 --num-episodes 100 --render True```

That will render game so you can see play
