### ISSUE TITLE
Performance of Breakout

### ISSUE THREAD

**Issue by yhcao6** [dgriff777/rl_a3c_pytorch#18]
Could I ask how long it takes to train Breakout from scratch to get the desire score (859.57 for Breakout-v3)?

Have You tried BreakoutNoFrameskip? This is a version without repetition and randomness.

Thanks!

**Comment by dgriff777** [comment]
Hi @yhcao6 that was different version then v-4 so not so comparable but on Breakout-v4 takes about 7hrs to average over 800reward but it often gets a score over 800 after just an hour in training. Gonna be adding some training graphs shortly for training with new A3G model

**Comment by yhcao6** [comment]
Thanks! When I specify the gpu_ids, it will report an error like this:
<img width="493" alt="2018-01-16 9 08 20" src="https://user-images.githubusercontent.com/22662425/34967342-e22e83e0-fa9c-11e7-9299-208885249cf6.png">
So I run in cpu mode, but the performance is also very surprising.
Does A3G means A3C-GPU version? 
I also wonder if you have train the model on some more difficult game like Super Mario? Thanks!

**Comment by dgriff777** [comment]
Looks like you are using python2. Have only ran gpu version on python3 sorry hadn't checked if if it ran ok with python2 for gpu version yet. can you run on python 3 or try just commenting the line out and see if it works
```
#mp.set_start_method('spawn')
```

**Comment by dgriff777** [comment]
Yes A3G means A3C-GPU version. New method I made to do GPU version of A3C that gives you benefits of GPU and CPU to speed training. Much faster for Atari, trains games as fast or faster than neuro-evolution on 700-1400 cpus and overall performance far greater

**Comment by dgriff777** [comment]
no haven't tried Super Mario but trained on some harder envs and Atari can be hard if you going for real superhuman like games scores not just mediocre scores seen on most benchmarks but used to success on many real world applications. Also did a continuous action version to solve BipedalWalkerHardcore env. See repo here: [a3c_continuous][1]

[1]:https://github.com/dgriff777/a3c_continuous

**Comment by yhcao6** [comment]
Thanks! I will have a try
