### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by lweitkamp** [dgriff777/rl_a3c_pytorch#27]
Hello, is it possible to get access to some of the pre-trained models? (specifically looking for sea quest, pong and space invaders but any or all would be brilliant)

**Comment by dgriff777** [comment]
which versions? i.e. -v0, v4, Deterministic-v4, NoFrameskip-v4...?

**Comment by lweitkamp** [comment]
I would love the NoFrameskip-v4, but Deterministic-v4 is not bad either. Also: what are the best parameters to tweak when training a more complexer game than pong?

**Comment by dgriff777** [comment]
Well looks like I deleted most but did locate one, the SeaquestNoFrameskip-v4. I added to repo. It performs flawlessly with a perfect score of 999,999 beating the game every time. Enjoy!! :)

oh and make sure to set time limit for environment to the max with  ```--max-episode-length 100000```

**Comment by dgriff777** [comment]
Sorry missed the parameters part lol. It will perform just fine how is. That said if you reduced the gamma parameter the agent will try to score quicker and if the environment is more deterministic reducing the tau parameter will introduce more variance

**Comment by lweitkamp** [comment]
Ah that's alright, thanks for the model! I'll try and see if i can fix some params to train easier. I've also heard that the latest version of pytorch kind of threw a lot of models off for some reason so maybe ill downgrade to 0.3 and try again.

**Comment by dgriff777** [comment]
Yeah the code is only tested up to 0.3. Have seen too many bugs in more current versions so not ready to upgrade till its more stable as no performance improvement in doing so as well.
