### ISSUE TITLE
Reward Smoothing

### ISSUE THREAD

**Issue by WangChen100** [dgriff777/rl_a3c_pytorch#32]
Hi, How do you think about reward smoothing.
The collected rewards have high variance. In order to show the tendency of reward curve, should we do some reward smoothing operation as same as tensorboard smoothing?
If so, which smoothing method should I choose, exponential smoothing or average smoothing?

**Comment by dgriff777** [comment]
Hi
Are you referring to rewards that are collected by model when learning, in which case they are being clipped to be between -1 and 1, which reduces the variance? Or are you referring to the actual testing final reward numbers?

**Comment by WangChen100** [comment]
Hi, thank you for your reply.
Agent receives a sum of rewards in every episode. However this sum value has high variance, as shown in following figure. 
![reward_total](https://user-images.githubusercontent.com/30588895/56850592-66c7d200-6937-11e9-8dc8-9e89cd40c830.png)
So is such a smoothing operation reasonable, as shown in following figure?
